# Generated by Django 3.1.7 on 2021-05-03 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('member_id', models.CharField(max_length=8, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=1024, null=True)),
                ('last_login', models.DateTimeField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
